### ISSUE TITLE
'command' isn't split according to regular shell rules (eg. quotes not interpreted)

### ISSUE THREAD

**Issue by olejorgenb** [riddlesio/match-wrapper#4]
Not a big deal of course.

But the readme do state: :) (emphasis mine)

> **command** The command to start the bot process. Can be any command; _if it works in your console, it should work here_.

To reproduce:

    run.sh: for x in "$@"; do echo "$x"; done

    "command": "run.sh 'this is _one_ argument'"

Produces:

    'this
    is
    ... (etc.)

Doesn't seems like the java sdk provides such [functionality](https://stackoverflow.com/questions/16722259/splitting-a-command-line-in-java) though.

An argument against could be that the exact details of how a command is split varies (?) from system to system and that multiple workarounds are available.

"Brute force" workaround in zsh:

    # Join all arguments into one string
    RAW="$*"                          
    # (z) parse the string according to shell rules
    # (Q) removes the quotes that z for some reason leave behind
    PARSED=(${(Q)${(z)RAW}})
    # Update positional arguments
    set $PARSED

**Comment by JimVanEeden** [comment]
What I meant by that line is the command to start any type of bot. So `python ./my_bot.py` for example. Maybe I could rephrase the line to make that more clear.

**Comment by JimVanEeden** [comment]
Fixed? with #6
