### ISSUE TITLE
Bot shutdown not working for golang?

### ISSUE THREAD

**Issue by nickvergessen** [riddlesio/match-wrapper#5]
I tried to port the "theaigames" golang connect four example to the new riddlesio version.

I ran `match-wrapper-1.3.2.jar` + `connect-four-engine-1.0.1.jar`, the bot can be found here:
https://gist.github.com/nickvergessen/61837b6356fd9d12b0660bd3dc43f3b6

The problem is that after the game is over (currently it only places in column 1, so after round4), the engine terminates and also prints:
```
Engine out: 'bot 0 ask action move'
Engine in: 'bot 0 place_disc 1'
Engine out: 'end'
Stopping...
Engine in: 'details'
Engine in: 'game'
Bot shut down.
Bot shut down.
Engine shut down.
Saving game...
Writing to result.json
Finished writing to result.json
Done.
```

But the bots didn't shutdown/terminate, but they run forever?!

I "fixed" this by looping for 5 seconds instead of `for true`, but would be nice if the bot is terminated correctly when shuting down.
Or is something wrong with my run command `go run .../main.go`

**Comment by JimVanEeden** [comment]
I'm not sure what's going on then. You can see `Bot shut down.` in the logs, so that means the match-wrapper killed the process. We use the exact same stuff on the servers and never have a problem with this, but it's kinda hard to see from here what the issue is exactly.

**Comment by nickvergessen** [comment]
Seems to work now, don't know what was wrong...
